name: dhatch_front_end
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  device_preview: ^1.2.0
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.3
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  uuid: ^3.0.6
  sqflite: ^2.4.1
  path: ^1.9.0
  fluttertoast: ^8.2.8
  google_maps_flutter: ^2.10.0
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  google_places_flutter: ^2.0.9
  geolocator: ^11.0.0
  google_maps_flutter_web: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Adamina
      fonts:
        - asset: assets/fonts/Adamina-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/dhatch_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/dhatch_icon.png"
